[build]
    command = "npm run build"
    publish = "dist"

[context.production.environment]
    ELEVENTY_ENV = "production"

[[headers]]
    for = "/*"
    [headers.values]
        X-Frame-Options = "DENY"
        X-XSS-Protection = "1; mode=block"
        X-Content-Type-Options = "nosniff"
        Referrer-Policy= "no-referrer-when-downgrade"

[[redirects]]
    from = "https://A11Ywebsites.netlify.app/*"
    to = "https://A11Ywebsites.com/:splat"
    status = 301
    force = true

[[redirects]]
    from = "*"
    to = "/404"
    status = 404
